project:
  type: default
  render:
    - "*.qmd"
    - "!template.qmd"

format:
  revealjs:
    theme: [simple, styles.scss]
    slide-level: 2
    incremental: false
    embed-resources: true
    slide-number: true
    show-slide-number: all
    navigation-mode: linear
    controls: true
    html-math-method: katex
    mermaid:
      theme: neutral
    code-line-numbers: true
    fig-align: center
    width: 1280
    height: 720
    margin: 0.08
    highlight-style: a11y
    title-slide-attributes:
      data-background-color: "#1c2430"

execute:
  eval: false
